# Generated by Django 3.1.3 on 2020-11-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallada_app', '0005_scrappeddata_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='data',
            field=models.JSONField(default=dict, verbose_name='User data'),
        ),
    ]
