# Generated by Django 3.1.3 on 2020-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallada_app', '0006_auto_20201129_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='data',
            field=models.TextField(default=dict, verbose_name='User data'),
        ),
    ]
